version: '3.8'

services:
  db:
    image: postgres:15
    container_name: pokedex-db
    restart: always
    environment:
      POSTGRES_USER: diego_admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: pokedex_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: